sudo apt install vim
sudo apt install git
sudo apt install gcc
sudo apt install gdb
sudo apt install ctags
sudo apt install tmux
sudo apt install curl
sudo apt install zsh
sudo apt install stow
sudo apt install htop
sudo apt install neofetch
