#!/bin/sh

VAR=$(xset -q|grep LED| awk '{ print $10 }')

#echo $VAR
case "$(xset -q|grep LED| awk '{ print $10 }')" in
  "00000000") KBD="English" ;;
  "00001000") KBD="Russian" ;;
  *) KBD="unknown" ;;
esac

echo $KBD
